#!/usr/bin/env bash
# install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx

# start nginx
sudo service nginx start

# enable nginx
sudo service nginx enable

# check nginx status
sudo service nginx status

# change root return code to Hello World!
echo "Hello World!" | sudo tee /var/www/html/index.html
