#!/usr/bin/env bash
# install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx

# start nginx
sudo service nginx start

# enable nginx
sudo service nginx enable

# check nginx status
sudo service nginx status

# change root return code to Hello World!
echo "Hello World!" | sudo tee /var/www/html/index.html
# Update Nginx configuration to add redirection
sudo sed -i '/^}$/i \ \n\trewrite ^/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Test Nginx configuration for syntax errors
sudo nginx -t

# Restart Nginx to apply changes
service nginx restart
