#!/usr/bin/env bash
# Installs, configures, and starts the server

# Update package list and install Nginx
apt-get update
apt-get -y install nginx

# Allow Nginx HTTP through firewall
sudo ufw allow 'Nginx HTTP'

# Create the necessary directories and set permissions
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

# Create a default index.html
echo 'Hello World!' > /var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Create the server configuration
SERVER_CONFIG=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://sketchfab.com/bluepeno/models permanent;
    }
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}"

# Write the configuration to the default site config file
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

# Start or restart Nginx service
if [ "$(pgrep -c nginx)" -le 0 ]; then
    service nginx start
else
    service nginx restart
fi

