#!/usr/bin/env bash
# installing Nginx
sudo apt update
sudo apt install nginx -y

# Add header
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
