#!/usr/bin/env bash
# installing Nginx
sudo su
apt update
apt install nginx -y

# Add header
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
