#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to install
# HAProxy and configures it to load balance to 2 servers using the
# roundrobin algorithm.

# Install Haproxy
sudo apt update
sudo apt-get install haproxy -y

# Config Haproxy
CONFIG_FILE="/etc/haproxy/haproxy.cfg"
write_config() {
  cat <<EOF > "$CONFIG_FILE"
frontend http
    bind *:80
    default_backend web-backend

backend web-backend
    balance roundrobin
    server web1 54.157.148.186:80 check
    server web2 54.158.189.0:80 check
EOF
}
sudo service haproxy restart

