#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to install
# HAProxy and configures it to load balance to 2 servers using the
# roundrobin algorithm.

# Install Haproxy
sudo apt update
sudo apt-get install haproxy -y

# Config Haproxy
echo "ENABLED=1" > /etc/default/haproxy
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 264389-web-01	 54.237.11.88:80 check
   server 264389-web-02	 54.152.129.152:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start


