#!/usr/bin/env bash
# Install Haproxy
STUDENT_ID="264389"

# Update package lists and install HAProxy
sudo apt update
sudo apt install haproxy -y

# Create HAProxy configuration file
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    maxconn 2000
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend main
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web1 ${STUDENT_ID}-web-01:80 check
    server web2 ${STUDENT_ID}-web-02:80 check

EOF

# Enable and start HAProxy
sudo systemctl enable haproxy
sudo systemctl start haproxy

