#!/usr/bin/env bash
# This bash script generates a MySQL dump and
# creates a compressed archive out of it.
D=$(date '+%d-%m-%Y')
mysql -uroot -p"$1" --all-databases > backup.sql
tar -czvf ./"$D".tar.gz backup.sql
