#!/usr/bin/env bash
# This script configures a server to be running NGINX and listening on port 80 of all the server's active IPV4 IPs.
echo "server {
     listen 80 default_server;
     listen [::]:80 default_server;
     root /var/www/html;
     index index.html index.htm index.nginx-debian.html;
     server_name _;
     location / {
     	      try_files \${uri} \${uri}/ =404;
     }
}" | sudo tee /etc/nginx/sites-available/default
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled
sudo service nginx restart
