#!/usr/bin/env bash
# Kills the process 7-highlander.

echo "$$" >/var/run/myscript.pid
terminator() {
	rm /var/run/myscript.pid
	exit
}
i=1
while [ i -lt 2 ]; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
