#!/usr/bin/env bash
# Using a While loop  and if to display "Best School" 10 times displays bad luck for the 4th loop iteration displays good luck for the 8th loop iteration displays Best School for the other iterations

i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 7 ]
    then 
        echo "good luck"
    elif [ $i -eq 3 ]
    then
        echo "bad luck"
    else
        echo "Best School"
    fi
    # Increment the counter
    i=$((i + 1))
done