#!/usr/bin/env bash
# Nested loops to print hours and miutes

Hour=0

while [ $Hour -lt 13 ]
do
    echo "Hour: $Hour"
    Minute=1
    while [ $Minute -lt 60 ]
    do
        echo $Minute
        # Increment the Minute
        Minute=$((Minute + 1))
    done

    # Increment the Hour
    Hour=$((Hour + 1))
done